language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install --require-hashes -r requirements.txt
  - pip install -r devel-requirements.txt
  - pip install -r extra-requirements.txt
  - pip install .

script: make check

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
