dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv run pip install pip==18.0
  - pipenv install --skip-lock --dev .[extra]

script: make check

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
