dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - export PYVERSION=$(python --version 2>&1|cut -d ' ' -f 2| cut -b 1,2,3)
  - if [ $PYVERSION = "2.7" ]; then export PIPVERSION=20.3; elif [ $PYVERSION = "3.5" ]; then export PIPVERSION=20.3; else export PIPVERSION=21.0; fi
  - pip install pipenv
  - pipenv run pip install pip==$PIPVERSION

install: pipenv install --skip-lock --dev .[extra]

script: make check

notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
