[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rerobots"
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "coverage",
    "pylint",
    "pytest",
    "responses",
    "tox",
]
