---
# configuration for GitHub Actions
name: rerobots Python client library tests
on:
    push:
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: ['3.10', 3.11, 3.12, 3.13]
        steps:
            - uses: actions/checkout@v4
            - name: Prepare Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'pip'
            - name: Install
              run: |
                pip install .[extra]
                pip install .[test]
            - name: Lint
              if: ${{ matrix.python-version == 3.12 }}
              run: |
                ruff format --check rerobots tests
            - name: Type checking
              if: ${{ matrix.python-version == 3.12 }}
              run: |
                mypy rerobots tests
            - name: Run tests
              run: |
                cd tests
                pytest -v --ignore=realserv/
